### ISSUE TITLE
Implement config feature

### ISSUE THREAD

**Issue by HaRo87** [HaRo87/go-bomd#3]
Design general config based on yaml file format which could look like:
```yaml
input:
  bom: bom.json
  template: template.tmpl
output:
  type: md
  name: report.md 
```

* It should be possible to generate a config via the `bomd generate config` command
* It should be possible to validate a config via the `bomd validate config` command
